myAnswer:-
    setof(N,sport(N,basketball),L1),
    writeln(L1),
    setof(A,K^(city(K,ontario),team(A,K)),L2),
    writeln(L2),
    setof(N,S^S2^(sport(N,S),sport(N,S2),S\=S2),K),
    writeln(K),
    findall((N,S),(sport(N,S),player(N,T),team(T,ottawa)),L3),
    writeln(L3),
    setof((N,S),T^(sport(N,S),player(N,T),team(T,ottawa)),L4), % Because there is duplicate player named marie in the database
    writeln(L4).

%make,myAnswer.

city(ottawa,ontario).
city(guelph,ontario).
city(kingston,ontario).
city(gatineau,quebec).
city(montreal,quebec).
team(ravens,ottawa).
team(ggs,ottawa).
team(gryphons,guelph).
team(queens,kingston).
team(torrents,gatineau).
team(stingers,montreal).
sport(annie,lacrosse).
sport(paul,crosscountry).
sport(suzy,ski).
sport(robert,basketball).
sport(tom,lacrosse).
sport(tim,ski).
sport(annie,ski).
sport(joe,basketball).
sport(robert,basketball).
sport(jane,basketball).
sport(marie,crosscountry).
sport(suzy,crosscountry).
sport(jack,ski).
sport(simon,lacrosse).
player(annie,gryphons).
player(tom,torrents).
player(jane,stingers).
player(marie,ggs).
player(joe,ravens).
player(jack,queens).
player(simon,ravens).
player(suzy,torrents).
player(paul,ggs).
player(marie,ggs).
player(simon,gryphons).

